spring:
  profiles.active: test
  datasource:
    url: xx
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties.hibernate.hbm2ddl.auto: update
    show-sql: true